version: "2"
services:
  elasticsearch:
    image: elasticsearch:5.1.1
    ports: 
      - 9200:9200
    container_name: elasticsearch
  kibana:
    image: kibana:5.1.1
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    container_name: kibana
  logstash:
    image: logstash:5.1.1
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    ports:
      - 5044:5044
    volumes:
      - ./logstash:/etc/logstash/conf.d
      - ./logstash/patterns:/opt/logstash/patterns
    depends_on:
      - elasticsearch
    container_name: logstash